name: cosypose
channels:
   - conda-forge
   - pytorch
dependencies:
  - python=3.7.6
  - pinocchio=2.3.1
  - assimp=4.1.0
  #- pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  #- torchvision=0.4.2=py37_cu101
  #- pytorch-gpu
  #- torchvision
  # pytorch for compute 8.0 & 8.6
  # https://github.com/moi90/pytorch_compute_capabilities/blob/main/table.md
  # https://github.com/pytorch/vision#installation
  #- pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  #- torchvision=0.8.2 # 0.8.2 <- pytorch=1.7.1
  - pytorch=1.8.1=py3.7_cuda11.1_cudnn8.0.5_0
  #- torchvision=0.9.1 # 0.9.1 <- pytorch=1.8.1
  - torchvision=0.9.1=py37_cu111 # 0.9.1 <- pytorch=1.8.1
  #- pytorch
  #- torchvision
  #- cudatoolkit=10.2
  - rclone
  - gxx_linux-64
  - git-lfs
  - ffmpeg
  - bzip2
  - git
  - cmake
  - pip
  - numpy
  - pillow
  - ipython
  - Cython
  - pip:
      #- ./deps/bullet3
      #- ./deps/job-runner
      - imageio
      - simplejson
      - opencv-python
      - opencv-contrib-python
      - torchnet
      - tqdm
      - lxml
      - transforms3d
      - distributed
      - joblib
      - pandas
      - xarray==0.14.1
      - pyarrow
      - matplotlib
      - bokeh
      - plyfile
      - trimesh
      - pycollada
      - shapely
      - wget
      - pypng
      - PyOpenGL
      - glumpy
      - ipdb
      - colorama
      - scikit-video
      - scikit-image
      - scikit-learn
      - pyyaml==5.1
      - ipykernel
      - scipy
      - pywavefront
      - jupyter-client
      - jupyter-core
      - jupyter-server-proxy
      - jupyterlab
      - jupyterlab-server
